gcc_options = -std=c++11 -Wall --pedantic-error
#gcc_options = -std=c++17 -Wall --pedantic-error

program : source
	cat $< > $@
source : source01 source02 source03
	cat source01 source02 source03 > source
hi :
	echo hi
hello :
	echo hello